services:
  web:
    build: 
      context: ./app
      dockerfile: dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:5006
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 5006:5006
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image:  postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
