services:
  web:
    build: 
      context: ./app
      dockerfile: dockerfile.prod
    command: gunicorn Intranet.wsgi:application --bind 0.0.0.0:5006
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 5006:5006
    env_file:
      - ./.env.prod


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
