FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# definiendo
#ENV APP_HOME=/home/app/web

# create the app user
#RUN addgroup --system app && adduser --system --group app

# chown all the files to the app user
#RUN chown -R app:app $APP_HOME

# change to the app user
#USER app